### PR TITLE
news: Add 1.5.4 entry

### PR DESCRIPTION
**Pull request by HashidaTKS**
SSIA

### CODE REVIEW

**Comment by HashidaTKS** [comment]
I plan to release 1.5.4 once this is merged.
Please give me permission to push to the `grntest` gem.

account: `hashida@clear-code.com

**Comment by kou** [comment]
I've added you to grntest owners.

**Comment by HashidaTKS** [comment]
Thank you.
I have released 1.5.4.

**Comment by kou** [comment]
Could you bump version for the next release?

**Comment by HashidaTKS** [comment]
Sure, I have created a new PR for it.
https://github.com/groonga/grntest/pull/7

**Pull request merged**
